// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  // Ruta del esquema principal
  schema: "prisma/schema.prisma",
  
  // Carpeta de almacenamiento de migraciones DDL
  migrations: {
    path: "prisma/migrations",
  },
  
  // Fuente de datos y cadena de conexión
  datasource: {
    url: env("DATABASE_URL"),
  },
});

